-- migrate:up
CREATE TABLE public.test (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT    NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
-- migrate:down
DROP TABLE IF EXISTS public.test
